-- The application accesses Postgres only through the trusted Express/Prisma API.
-- Enabling RLS without public policies prevents Supabase's PostgREST roles from
-- reading or mutating these tables while preserving access for the table owner.

ALTER TABLE "public"."Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Branch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Room" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."StaffMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."PasswordResetToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."UserInvitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."AuthSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."AttendanceEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackAttendanceRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackCorrectionRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackAuditEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackChallenge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackKioskDevice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."FaceTrackKioskChallenge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Service" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Appointment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Treatment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."InventoryItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."InventoryMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Sale" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."SaleItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ClinicPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."GiftCertificate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Lead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadFollowUp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadTouchpoint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ExternalLeadIdentity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadConversion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."LeadAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."SmsTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."MarketingCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Expense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Discount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."SystemSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."UploadAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."_prisma_migrations" ENABLE ROW LEVEL SECURITY;

-- Make the server-only access model explicit. These restrictive policies keep
-- PostgREST's public roles denied even if permissive policies are added later.

DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Client";
CREATE POLICY "deny_direct_api_access" ON "public"."Client" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Branch";
CREATE POLICY "deny_direct_api_access" ON "public"."Branch" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Room";
CREATE POLICY "deny_direct_api_access" ON "public"."Room" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."StaffMember";
CREATE POLICY "deny_direct_api_access" ON "public"."StaffMember" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Account";
CREATE POLICY "deny_direct_api_access" ON "public"."Account" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."PasswordResetToken";
CREATE POLICY "deny_direct_api_access" ON "public"."PasswordResetToken" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."UserInvitation";
CREATE POLICY "deny_direct_api_access" ON "public"."UserInvitation" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."AuthSession";
CREATE POLICY "deny_direct_api_access" ON "public"."AuthSession" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."AttendanceEvent";
CREATE POLICY "deny_direct_api_access" ON "public"."AttendanceEvent" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackProfile";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackProfile" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackAttendanceRecord";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackAttendanceRecord" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackCorrectionRequest";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackCorrectionRequest" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackAuditEntry";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackAuditEntry" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackChallenge";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackChallenge" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackPolicy";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackPolicy" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackKioskDevice";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackKioskDevice" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."FaceTrackKioskChallenge";
CREATE POLICY "deny_direct_api_access" ON "public"."FaceTrackKioskChallenge" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Service";
CREATE POLICY "deny_direct_api_access" ON "public"."Service" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Appointment";
CREATE POLICY "deny_direct_api_access" ON "public"."Appointment" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Treatment";
CREATE POLICY "deny_direct_api_access" ON "public"."Treatment" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."InventoryItem";
CREATE POLICY "deny_direct_api_access" ON "public"."InventoryItem" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."InventoryMovement";
CREATE POLICY "deny_direct_api_access" ON "public"."InventoryMovement" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Sale";
CREATE POLICY "deny_direct_api_access" ON "public"."Sale" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."SaleItem";
CREATE POLICY "deny_direct_api_access" ON "public"."SaleItem" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."ClinicPackage";
CREATE POLICY "deny_direct_api_access" ON "public"."ClinicPackage" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."GiftCertificate";
CREATE POLICY "deny_direct_api_access" ON "public"."GiftCertificate" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Lead";
CREATE POLICY "deny_direct_api_access" ON "public"."Lead" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadActivity";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadActivity" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadFollowUp";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadFollowUp" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadTouchpoint";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadTouchpoint" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."ExternalLeadIdentity";
CREATE POLICY "deny_direct_api_access" ON "public"."ExternalLeadIdentity" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadIntegration";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadIntegration" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."WebhookEvent";
CREATE POLICY "deny_direct_api_access" ON "public"."WebhookEvent" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadConversion";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadConversion" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."LeadAssignment";
CREATE POLICY "deny_direct_api_access" ON "public"."LeadAssignment" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."SmsTemplate";
CREATE POLICY "deny_direct_api_access" ON "public"."SmsTemplate" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."MarketingCampaign";
CREATE POLICY "deny_direct_api_access" ON "public"."MarketingCampaign" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Expense";
CREATE POLICY "deny_direct_api_access" ON "public"."Expense" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."Discount";
CREATE POLICY "deny_direct_api_access" ON "public"."Discount" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."AuditLog";
CREATE POLICY "deny_direct_api_access" ON "public"."AuditLog" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."SystemSetting";
CREATE POLICY "deny_direct_api_access" ON "public"."SystemSetting" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."UploadAsset";
CREATE POLICY "deny_direct_api_access" ON "public"."UploadAsset" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "deny_direct_api_access" ON "public"."_prisma_migrations";
CREATE POLICY "deny_direct_api_access" ON "public"."_prisma_migrations" AS RESTRICTIVE FOR ALL TO "anon", "authenticated" USING (false) WITH CHECK (false);
