import {
  BarChart3,
  BookOpen,
  Camera,
  Boxes,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardCheck,
  Gift,
  Globe2,
  HeartPulse,
  Home,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  MessageSquareText,
  ReceiptText,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  UserCheck,
  Users,
  WalletCards,
} from "lucide-react";

export const navItems = [
  { id: "my-workspace", path: "/my-workspace", label: "My Workspace", icon: UserCheck, section: "main" },
  { id: "overview", path: "/dashboard", label: "Dashboard", icon: LayoutDashboard, section: "main" },
  { id: "applications", path: "/applications", label: "Applications", icon: LayoutGrid, section: "main" },
  { id: "appointments", path: "/appointments", label: "Appointments", icon: CalendarDays, section: "main" },
  { id: "clients", path: "/clients", label: "Clients", icon: Users, section: "main" },
  { id: "leads", path: "/leads", label: "Leads", icon: Inbox, section: "main" },
  { id: "pos", path: "/pos", label: "POS", icon: WalletCards, section: "clinic-operations" },
  { id: "card-view", path: "/card-view", label: "Card View", icon: ClipboardCheck, section: "clinic-operations" },
  { id: "room-view", path: "/room-view", label: "Room View", icon: Home, section: "clinic-operations" },
  { id: "treatments", path: "/treatments", label: "Treatments", icon: HeartPulse, section: "clinic-operations" },
  { id: "services", path: "/services", label: "Services", icon: Sparkles, section: "clinic-operations" },
  { id: "packages", path: "/packages", label: "Packages", icon: Gift, section: "clinic-operations" },
  { id: "booking", path: "/online-booking", label: "Online Booking", icon: Globe2, section: "clinic-operations" },
  { id: "staff-view", path: "/staff-schedule", label: "Staff Schedule", icon: UserCheck, section: "staff-branches" },
  { id: "staff", path: "/staff", label: "Staff Management", icon: BriefcaseBusiness, section: "staff-branches" },
  { id: "facetrack-attendance", path: "/attendance", label: "FaceTrack Attendance", icon: Camera, section: "staff-branches" },
  { id: "branches", path: "/branches", label: "Branches", icon: Store, section: "staff-branches" },
  { id: "inventory", path: "/inventory", label: "Inventory", icon: Boxes, section: "inventory-finance" },
  { id: "expenses", path: "/expenses", label: "Expenses", icon: ReceiptText, section: "inventory-finance" },
  { id: "reports", path: "/reports", label: "Reports", icon: BarChart3, section: "inventory-finance" },
  { id: "sms", path: "/marketing", label: "Marketing", icon: MessageSquareText, section: "marketing" },
  { id: "flipbooks", path: "/flipbooks", label: "Flipbooks", icon: BookOpen, section: "marketing" },
  { id: "settings", path: "/settings", label: "Settings", icon: Settings, section: "system" },
  { id: "support", path: "/support", label: "Support", icon: ShieldCheck, section: "support" },
];

export const navSections = [
  { id: "main", label: "Main" },
  { id: "clinic-operations", label: "Clinic Operations" },
  { id: "staff-branches", label: "Staff & Branches" },
  { id: "inventory-finance", label: "Inventory & Finance" },
  { id: "marketing", label: "Marketing" },
  { id: "system", label: "System" },
  { id: "support", label: "Support" },
].map((section) => ({
  ...section,
  items: navItems.filter((item) => item.section === section.id),
}));

export const coreClinicModules = ["clients", "appointments", "treatments"];
