export const assets = {
  logo: "/brand/zenshotech-logo.svg",
  logoWhite: "/brand/zenshotech-logo.svg",
  doctor: "/brand/dr-mace.jpg",
  clinic: "/brand/clinic.jpg",
  clinicDavao: "/brand/clinic-davao.jpg",
  resultOne: "/brand/result-1.jpg",
  resultTwo: "/brand/result-2.jpg",
};

export const serviceCategories = [
  "Facial Treatments",
  "Injectables & Contour Enhancements",
  "Skin Rejuvenation & Specialized Treatments",
  "Laser Treatments & Energy-Based Devices",
  "IV Drips",
  "Packages",
  "Add-ons",
  "Consultations",
  "Retail Add-ons",
];

const completeWorkspaceAccess = ["my-workspace", "overview", "applications", "facetrack-attendance", "pos", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "services", "inventory", "packages", "leads", "sms", "flipbooks", "staff", "branches", "expenses", "payroll", "reports", "booking", "settings", "support"];

export const roleAccess = {
  "Demo User": completeWorkspaceAccess,
  "Super Admin": completeWorkspaceAccess,
  Admin: ["pos", "staff", "facetrack-attendance"],
  Owner: completeWorkspaceAccess,
  "Business Owner": completeWorkspaceAccess,
  "Branch Manager": ["pos", "staff", "facetrack-attendance"],
  Receptionist: ["pos"],
  Cashier: ["pos"],
  Doctor: ["pos"],
  Nurse: ["pos"],
  "Head Nurse": ["pos"],
  Aesthetician: ["pos"],
  "Head Aesthetician": ["pos"],
  "Inventory Staff": ["pos"],
  "Marketing Staff": ["pos"],
  Employee: ["pos"],
};

export const branches = [
  {
    id: "br-davao",
    name: "Mace Davao",
    city: "Davao",
    address: "Davao City",
    phone: "0917 886 2104",
    hours: "Mon-Sat 10:00 AM - 7:00 PM; Sun 1:00 PM - 5:00 PM",
    operatingHours: {
      monday: { open: "10:00", close: "19:00", closed: false },
      tuesday: { open: "10:00", close: "19:00", closed: false },
      wednesday: { open: "10:00", close: "19:00", closed: false },
      thursday: { open: "10:00", close: "19:00", closed: false },
      friday: { open: "10:00", close: "19:00", closed: false },
      saturday: { open: "10:00", close: "19:00", closed: false },
      sunday: { open: "13:00", close: "17:00", closed: false },
    },
    couches: 0,
    rooms: ["Consult Room", "Treatment Room", "Laser Room"],
    staff: 6,
    devices: ["Mace Thermatight", "Diode Hair Removal", "Rejuvelight"],
    image: assets.clinicDavao,
  },
];

export const initialClients = [
  {
    id: "cl-celine",
    fullName: "Celine Ann Hernandez",
    mobile: "0917 443 2210",
    email: "celine.hernandez@example.com",
    gender: "Female",
    birthday: "1992-09-14",
    address: "BGC, Taguig",
    city: "Taguig",
    emergency: "Marco Hernandez - 0917 200 9911",
    branch: "Mace Davao",
    source: "Website",
    referral: "MACE website",
    medicalNotes: "Sensitive skin. Prefers doctor review before injectables.",
    allergies: "None declared",
    contraindications: "Review before laser during active irritation.",
    skinConcerns: "Texture, dullness, early fine lines",
    treatmentGoals: "Natural glow and refreshed face",
    consentStatus: "Signed",
    marketingOptIn: true,
    preferredStaff: "Dr. Mace",
    tag: "VIP",
    retention: "Returning",
    lastVisit: "2026-07-01",
    nextVisit: "2026-07-08",
    balance: 0,
    packageBalance: "4 of 6 Glow Maintenance sessions",
    giftBalance: 0,
  },
  {
    id: "cl-mika",
    fullName: "Mika Santos",
    mobile: "0928 842 1180",
    email: "mika.santos@example.com",
    gender: "Female",
    birthday: "1995-02-21",
    address: "Makati City",
    city: "Makati",
    emergency: "Lia Santos - 0928 500 4422",
    branch: "Mace Davao",
    source: "Instagram",
    referral: "Instagram",
    medicalNotes: "First consultation. Asked for acne plan.",
    allergies: "Latex sensitivity",
    contraindications: "Avoid latex supplies.",
    skinConcerns: "Acne, congestion",
    treatmentGoals: "Clearer skin and maintenance routine",
    consentStatus: "Pending",
    marketingOptIn: true,
    preferredStaff: "Nurse Ana",
    tag: "New",
    retention: "New",
    lastVisit: "2026-06-28",
    nextVisit: "2026-07-05",
    balance: 1500,
    packageBalance: "None",
    giftBalance: 0,
  },
  {
    id: "cl-andrea",
    fullName: "Andrea Lee",
    mobile: "0916 092 8821",
    email: "andrea.lee@example.com",
    gender: "Female",
    birthday: "1988-11-08",
    address: "Davao City",
    city: "Davao",
    emergency: "Ben Lee - 0916 120 8877",
    branch: "Mace Davao",
    source: "Referral",
    referral: "Friend referral",
    medicalNotes: "Prefers non-invasive lifting treatments.",
    allergies: "None declared",
    contraindications: "None declared",
    skinConcerns: "Laxity, facial contour",
    treatmentGoals: "Lifted but natural result",
    consentStatus: "Signed",
    marketingOptIn: false,
    preferredStaff: "Dr. Aria Tan",
    tag: "Returning",
    retention: "Returning",
    lastVisit: "2026-06-21",
    nextVisit: "2026-07-10",
    balance: 4500,
    packageBalance: "1 of 3 Lift & Define sessions",
    giftBalance: 2000,
  },
  {
    id: "cl-trisha",
    fullName: "Trisha Uy",
    mobile: "0915 883 6174",
    email: "trisha.uy@example.com",
    gender: "Female",
    birthday: "1997-05-18",
    address: "Quezon City",
    city: "Quezon City",
    emergency: "Ana Uy - 0915 109 2117",
    branch: "Mace Davao",
    source: "Facebook",
    referral: "Facebook page",
    medicalNotes: "Acne scar program in progress.",
    allergies: "None declared",
    contraindications: "Avoid laser if skin is sunburned.",
    skinConcerns: "Acne marks, texture",
    treatmentGoals: "Smooth texture and less visible scars",
    consentStatus: "Signed",
    marketingOptIn: true,
    preferredStaff: "Nurse Bea",
    tag: "Follow-up",
    retention: "At risk",
    lastVisit: "2026-06-19",
    nextVisit: "2026-07-04",
    balance: 0,
    packageBalance: "3 of 4 Acne Recovery sessions",
    giftBalance: 0,
  },
];

export const initialAppointments = [];

export const initialInventory = [
  { id: "inv-skin-booster", item: "Skin Booster Vials", sku: "INJ-SBV-10", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "vial", packQty: 10, beginning: 30, stock: 18, branch: "Mace Davao", location: "Cold storage", reorder: 10, expiry: "2026-11-30", batch: "SBV-2607", supplier: "Derma Supply PH", cost: 3200, price: 0 },
  { id: "inv-botox", item: "Botox Units", sku: "INJ-BTX-100", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "unit", packQty: 100, beginning: 30, stock: 9, branch: "Mace Davao", location: "Cold storage", reorder: 12, expiry: "2026-09-20", batch: "BTX-2605", supplier: "Aesthetic Med PH", cost: 240, price: 0 },
  { id: "inv-filler", item: "Filler Syringe", sku: "INJ-FLR-01", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "syringe", packQty: 1, beginning: 12, stock: 7, branch: "Mace Davao", location: "Cold storage", reorder: 5, expiry: "2026-10-15", batch: "FLR-2606", supplier: "Aesthetic Med PH", cost: 5800, price: 0 },
  { id: "inv-syringe", item: "Sterile Syringe Kit", sku: "SUP-SYK-01", brand: "MedSafe", category: "Supplies", type: "Consumable", unit: "kit", packQty: 1, beginning: 80, stock: 45, branch: "Mace Davao", location: "Procedure room", reorder: 25, expiry: "2027-01-12", batch: "SYK-2604", supplier: "MedSafe Supplies", cost: 90, price: 0 },
  { id: "inv-post-cream", item: "Post-care Cream", sku: "RTL-PCC-30", brand: "MACE Skin", category: "Retail", type: "Retail", unit: "tube", packQty: 1, beginning: 50, stock: 34, branch: "Mace Davao", location: "Retail shelf", reorder: 20, expiry: "2027-04-30", batch: "PCC-2607", supplier: "MACE Skin Lab", cost: 420, price: 1200, image: "/brand/products/post-care-cream.png" },
  { id: "inv-laser-tips", item: "Laser Tips", sku: "DEV-LTP-01", brand: "Device Care", category: "Device Consumables", type: "Consumable", unit: "tip", packQty: 1, beginning: 18, stock: 6, branch: "Mace Davao", location: "Laser room", reorder: 8, expiry: "2026-12-01", batch: "LTP-2602", supplier: "Device Care PH", cost: 950, price: 0 },
  { id: "inv-cleanser-kit", item: "Cleanser Travel Kit", sku: "RTL-CLK-01", brand: "MACE Skin", category: "Retail", type: "Retail", unit: "kit", packQty: 1, beginning: 36, stock: 24, branch: "Mace Davao", location: "Retail shelf", reorder: 12, expiry: "2027-02-18", batch: "CLK-2606", supplier: "MACE Skin Lab", cost: 520, price: 1500, image: "/brand/products/cleanser-travel-kit.png" },
  { id: "inv-iv-kit", item: "IV Glow Kit", sku: "IV-GLW-01", brand: "MACE Wellness", category: "IV Drips", type: "Consumable", unit: "kit", packQty: 1, beginning: 22, stock: 11, branch: "Mace Davao", location: "IV Lounge", reorder: 8, expiry: "2026-08-30", batch: "IVG-2605", supplier: "Wellness Supply PH", cost: 1800, price: 0 },
  { id: "inv-ultralift", item: "Ultralift Cartridge", sku: "DEV-ULT-01", brand: "MACE Devices", category: "Device Consumables", type: "Consumable", unit: "cartridge", packQty: 1, beginning: 10, stock: 4, branch: "Mace Davao", location: "Device suite", reorder: 4, expiry: "2027-05-01", batch: "ULT-2607", supplier: "Device Care PH", cost: 4200, price: 0 },
];

export const initialTreatments = [];

export const initialPackages = [
  { id: "pkg-001", name: "Glow Maintenance Plan", clientId: "cl-celine", client: "Celine Ann Hernandez", sessions: 6, used: 2, expires: "", branch: "All branches", transferable: false, status: "Active", price: 18500 },
  { id: "pkg-002", name: "Acne Recovery Plan", clientId: "cl-trisha", client: "Trisha Uy", sessions: 4, used: 1, expires: "", branch: "Mace Davao", transferable: false, status: "Active", price: 14000 },
  { id: "pkg-003", name: "Lift & Define Plan", clientId: "cl-andrea", client: "Andrea Lee", sessions: 3, used: 0, expires: "", branch: "All branches", transferable: true, status: "Pending", price: 48000 },
];

export const initialGiftCertificates = [
  { id: "gc-001", code: "MACE-GLOW-1000", client: "Walk-in buyer", balance: 1000, expires: "2026-12-31", status: "Active" },
  { id: "gc-002", code: "MACE-FACE-5000", client: "Andrea Lee", balance: 2000, expires: "2026-11-30", status: "Partially used" },
];

export const initialLeads = [];

// Staff profiles are created by clinic administrators and are never preloaded.
export const initialStaff = [];

export const initialExpenses = [
  { id: "ex-001", date: "2026-07-02", name: "Clinic supplies", category: "Supplies", branch: "Mace Davao", amount: 12400, method: "Bank Transfer", approver: "Owner", status: "Approved", notes: "Monthly replenishment.", receipt: "Attached" },
  { id: "ex-002", date: "2026-07-01", name: "Utilities", category: "Utilities", branch: "Mace Davao", amount: 8900, method: "Cash", approver: "Branch Manager", status: "Approved", notes: "Electric and water.", receipt: "Attached" },
  { id: "ex-003", date: "2026-06-30", name: "Training refresh", category: "Training", branch: "Mace Davao", amount: 18000, method: "Credit Card", approver: "Owner", status: "For approval", notes: "Device protocol refresh.", receipt: "Pending" },
  { id: "ex-004", date: "2026-06-28", name: "Instagram campaign", category: "Marketing", branch: "All branches", amount: 22000, method: "Credit Card", approver: "Owner", status: "Approved", notes: "Promo ads.", receipt: "Attached" },
];

export const initialTransactions = [
  { id: "txn-260703-001", invoice: "MACE-260703-001", date: "2026-07-03", time: "10:15", client: "Walk-in", branch: "Mace Davao", staff: "Nurse Ana", items: [{ name: "Mace Signature Facial", type: "Service", qty: 1, price: 3200 }], subtotal: 3200, discount: 0, total: 3200, payments: [{ method: "GCash", amount: 3200 }], status: "Paid", notes: "Walk-in service." },
  { id: "txn-260702-001", invoice: "MACE-260702-001", date: "2026-07-02", time: "14:20", client: "Celine Ann Hernandez", branch: "Mace Davao", staff: "Dr. Mace", items: [{ name: "Skin Booster Treatment", type: "Service", qty: 1, price: 9500 }, { name: "Post-care Cream", type: "Product", qty: 1, price: 1200 }], subtotal: 10700, discount: 700, total: 10000, payments: [{ method: "Cash", amount: 6000 }, { method: "Credit Card", amount: 4000 }], status: "Paid", notes: "VIP courtesy discount." },
  { id: "txn-260701-002", invoice: "MACE-260701-002", date: "2026-07-01", time: "17:05", client: "Andrea Lee", branch: "Mace Davao", staff: "Dr. Aria Tan", items: [{ name: "Mace Ultralift", type: "Service", qty: 1, price: 18000 }], subtotal: 18000, discount: 0, total: 18000, payments: [{ method: "Bank Transfer", amount: 13500 }], status: "Partial", notes: "Balance due on next visit." },
];

export const initialDiscounts = [
  { id: "disc-senior", name: "Senior Citizen", type: "Percentage", value: 20, active: true, permission: "Cashier", applicable: "Services and products", expiry: "None", usage: 8 },
  { id: "disc-pwd", name: "PWD", type: "Percentage", value: 20, active: true, permission: "Cashier", applicable: "Services and products", expiry: "None", usage: 4 },
  { id: "disc-vip", name: "VIP", type: "Fixed amount", value: 700, active: true, permission: "Branch Manager", applicable: "Selected clients", expiry: "2026-12-31", usage: 12 },
  { id: "disc-owner", name: "Owner's Discount", type: "Percentage", value: 100, active: true, permission: "Owner", applicable: "Owner approval only", expiry: "None", usage: 2 },
  { id: "disc-birthday", name: "Birthday Promo", type: "Percentage", value: 10, active: true, permission: "Receptionist", applicable: "Birthday month", expiry: "2026-12-31", usage: 15 },
];

export const initialSmsTemplates = [
  { id: "sms-confirm", name: "Appointment confirmation", category: "Appointment", text: "Hi {{client}}, your ZenshoTech appointment for {{service}} is confirmed on {{date}} at {{time}}. Reply YES to confirm.", active: true },
  { id: "sms-reminder", name: "Appointment reminder", category: "Appointment", text: "Hi {{client}}, this is your gentle reminder for your ZenshoTech visit tomorrow at {{time}}. We love your face.", active: true },
  { id: "sms-aftercare", name: "Post-treatment follow-up", category: "Aftercare", text: "Hi {{client}}, thank you for visiting ZenshoTech. Please follow your aftercare notes and message us for any concerns.", active: true },
  { id: "sms-birthday", name: "Birthday greeting", category: "Marketing", text: "Happy birthday month, {{client}}. A beautiful month deserves a ZenshoTech glow.", active: true },
  { id: "sms-winback", name: "Win-back campaign", category: "Marketing", text: "Hi {{client}}, it has been a while. Book your personalized care session with ZenshoTech this week.", active: true },
];

export const initialCampaigns = [
  {
    id: "cmp-001",
    name: "July Glow Reminder",
    segment: "Inactive clients",
    channel: "SMS",
    templateId: "sms-winback",
    subject: "Your ZenshoTech glow is waiting",
    message: "Hi {{client}}, it has been a while. Book your personalized care session with ZenshoTech this week.",
    sent: 180,
    booked: 24,
    credits: 180,
    status: "Sent",
  },
  {
    id: "cmp-002",
    name: "Birthday Month Care",
    segment: "Birthday month",
    channel: "SMS",
    templateId: "sms-birthday",
    subject: "Birthday month care from ZenshoTech",
    message: "Happy birthday month, {{client}}. A beautiful month deserves a ZenshoTech glow.",
    sent: 42,
    booked: 9,
    credits: 42,
    status: "Scheduled",
  },
  {
    id: "cmp-003",
    name: "Skin Booster Upsell",
    segment: "Facial clients",
    channel: "Email",
    templateId: "",
    subject: "Skin booster appointments are open",
    message: "Hi {{client}}, your next skin booster session can help keep your glow fresh. Reply to this email to reserve your preferred time.",
    sent: 0,
    booked: 0,
    credits: 0,
    status: "Draft",
  },
];

export const initialSettings = {
  company: "ZenshoTech",
  productName: "ZenshoTech",
  currency: "PHP",
  taxMode: "VAT exclusive",
  taxRate: 12,
  receiptFooter: "The brand behind beautiful faces.",
  invoicePrefix: "ZENSHO",
  smsCredits: 8400,
  managerApproval: true,
  marketingSenderName: "ZenshoTech",
  marketingReplyTo: "hello@macebydrmace.com",
  marketingUnsubscribeText: "You are receiving this because you opted in to ZenshoTech marketing. Unsubscribe at any time.",
  backup: "Daily backup-ready",
  hiddenSaasPlans: true,
  paymentMethods: ["Cash", "Card", "Bank/Online Transfer", "GCash", "Maya", "Check", "Gift Certificate", "Offset", "Salary Deduction", "Shopee"],
  expenseCategories: ["Salary", "Supplies", "Utilities", "Rent", "Marketing", "Training", "Equipment", "Maintenance", "Professional fees", "Other"],
  productCategories: ["Injectables", "Retail", "Device Consumables", "Supplies", "IV Drips"],
  serviceCategories,
};
