export const assets = {
  logo: "/brand/mace-logo.png",
  logoWhite: "/brand/mace-logo-white.svg",
  doctor: "/brand/dr-mace.jpg",
  clinic: "/brand/clinic.jpg",
  clinicDavao: "/brand/clinic-davao.jpg",
  resultOne: "/brand/result-1.jpg",
  resultTwo: "/brand/result-2.jpg",
};

export const serviceCategories = [
  "Facial Treatments",
  "Injectables & Contour Enhancements",
  "Skin Rejuvenation & Specialized Treatments",
  "Laser Treatments & Energy-Based Devices",
  "IV Drips",
  "Packages",
  "Consultations",
  "Retail Add-ons",
];

export const users = [
  { id: "u-owner", name: "Dr. Mace", role: "Owner", email: "owner@mace.test", branch: "All branches" },
  { id: "u-admin", name: "Admin Sofia", role: "Super Admin", email: "admin@mace.test", branch: "All branches" },
  { id: "u-manager", name: "Mika Santos", role: "Branch Manager", email: "manager@mace.test", branch: "Mace BGC" },
  { id: "u-reception", name: "Ria Lim", role: "Receptionist", email: "frontdesk@mace.test", branch: "Mace BGC" },
  { id: "u-cashier", name: "Cathy Go", role: "Cashier", email: "cashier@mace.test", branch: "Mace BGC" },
  { id: "u-doctor", name: "Dr. Aria Tan", role: "Doctor", email: "doctor@mace.test", branch: "Mace BGC" },
  { id: "u-nurse", name: "Nurse Ana", role: "Nurse / Aesthetician", email: "nurse@mace.test", branch: "Mace Davao" },
  { id: "u-nurse-bea", name: "Nurse Bea", role: "Nurse / Aesthetician", email: "bea@mace.test", branch: "Mace Davao" },
  { id: "u-inventory", name: "Bea Cruz", role: "Inventory Staff", email: "inventory@mace.test", branch: "Mace Davao" },
  { id: "u-marketing", name: "Pat Lee", role: "Marketing Staff", email: "marketing@mace.test", branch: "All branches" },
  { id: "u-employee", name: "Ella Reyes", role: "Employee", email: "employee@mace.test", branch: "Mace BGC" },
];

export const roleAccess = {
  "Super Admin": ["my-workspace", "overview", "applications", "pos", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "services", "inventory", "packages", "leads", "sms", "staff", "branches", "expenses", "reports", "booking", "settings", "support"],
  Owner: ["my-workspace", "overview", "applications", "pos", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "services", "inventory", "packages", "leads", "sms", "staff", "branches", "expenses", "reports", "booking", "settings", "support"],
  "Branch Manager": ["my-workspace", "overview", "applications", "pos", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "services", "inventory", "packages", "leads", "sms", "staff", "expenses", "reports", "booking", "support"],
  Receptionist: ["my-workspace", "overview", "applications", "pos", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "packages", "leads", "sms", "booking", "support"],
  Cashier: ["my-workspace", "overview", "applications", "pos", "card-view", "clients", "packages", "expenses", "reports", "support"],
  Doctor: ["my-workspace", "overview", "applications", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "services", "reports", "support"],
  "Nurse / Aesthetician": ["my-workspace", "overview", "applications", "card-view", "staff-view", "room-view", "appointments", "clients", "treatments", "inventory", "support"],
  "Inventory Staff": ["my-workspace", "overview", "applications", "inventory", "services", "reports", "support"],
  "Marketing Staff": ["my-workspace", "overview", "applications", "clients", "leads", "sms", "booking", "reports", "support"],
  Employee: ["my-workspace", "overview", "applications", "appointments", "clients", "support"],
};

export const branches = [
  {
    id: "br-bgc",
    name: "Mace BGC",
    city: "Taguig",
    address: "Bonifacio Global City, Taguig",
    phone: "0917 109 8462",
    hours: "10:00 AM - 8:00 PM",
    rooms: ["Room 1", "Room 2", "Laser Room", "Device Suite"],
    staff: 8,
    devices: ["Mace Ultralift", "Mace Sculpt", "Picowhite"],
    image: assets.clinic,
  },
  {
    id: "br-davao",
    name: "Mace Davao",
    city: "Davao",
    address: "Davao City",
    phone: "0917 886 2104",
    hours: "9:00 AM - 7:00 PM",
    rooms: ["Consult Room", "Treatment Room", "Laser Room"],
    staff: 6,
    devices: ["Mace Thermatight", "Diode Hair Removal", "Rejuvelight"],
    image: assets.clinicDavao,
  },
];

export const initialServices = [
  { id: "svc-consult", name: "Aesthetic Consultation", category: "Consultations", duration: 45, price: 1500, commission: "Doctor 10%", consumables: [], branches: ["Mace BGC", "Mace Davao"], staff: ["Doctor"], room: "Consult Room", active: true, pos: true, description: "Personalized skin and wellness assessment.", contraindications: "Review allergies and pregnancy status.", aftercare: "Follow treatment plan." },
  { id: "svc-signature-facial", name: "Mace Signature Facial", category: "Facial Treatments", duration: 60, price: 3200, commission: "Aesthetician 8%", consumables: ["Cleanser Travel Kit", "Post-care Cream"], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "Treatment Room", active: true, pos: true, description: "Premium glow facial for refreshed skin.", contraindications: "Open wounds or active infection.", aftercare: "Hydrate and use sunscreen." },
  { id: "svc-classic-facial", name: "Classic Facial", category: "Facial Treatments", duration: 55, price: 2500, commission: "Aesthetician 8%", consumables: ["Post-care Cream"], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "Treatment Room", active: true, pos: true, description: "Deep cleansing and gentle extraction.", contraindications: "Active irritation.", aftercare: "Avoid exfoliants for 48 hours." },
  { id: "svc-bb-glow", name: "BB Glow + BB Blush Facial", category: "Facial Treatments", duration: 75, price: 4800, commission: "Aesthetician 8%", consumables: ["Post-care Cream"], branches: ["Mace BGC"], staff: ["Nurse / Aesthetician"], room: "Treatment Room", active: true, pos: true, description: "Luminous complexion treatment.", contraindications: "Sensitivity or recent peel.", aftercare: "No makeup for 24 hours." },
  { id: "svc-acne-facial", name: "Acne Facial", category: "Facial Treatments", duration: 70, price: 3600, commission: "Aesthetician 8%", consumables: ["Post-care Cream"], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "Treatment Room", active: true, pos: true, description: "Acne-focused care with calming protocol.", contraindications: "Severe inflammation requires doctor review.", aftercare: "Use prescribed routine only." },
  { id: "svc-botox", name: "Botulinum Toxin Injections", category: "Injectables & Contour Enhancements", duration: 45, price: 12000, commission: "Doctor 12%", consumables: ["Botox Units", "Sterile Syringe Kit"], branches: ["Mace BGC", "Mace Davao"], staff: ["Doctor"], room: "Procedure Room", active: true, pos: true, description: "Advanced wrinkle softening and contour care.", contraindications: "Pregnancy, infection, neuromuscular condition.", aftercare: "No heavy exercise for 24 hours." },
  { id: "svc-filler", name: "Dermal Fillers", category: "Injectables & Contour Enhancements", duration: 60, price: 18000, commission: "Doctor 12%", consumables: ["Filler Syringe", "Sterile Syringe Kit"], branches: ["Mace BGC"], staff: ["Doctor"], room: "Procedure Room", active: true, pos: true, description: "Volume and contour enhancement.", contraindications: "Active infection or allergy history.", aftercare: "Avoid pressure and heat for 48 hours." },
  { id: "svc-skin-booster", name: "Skin Booster Treatment", category: "Injectables & Contour Enhancements", duration: 60, price: 9500, commission: "Doctor 10%", consumables: ["Skin Booster Vials", "Sterile Syringe Kit"], branches: ["Mace BGC", "Mace Davao"], staff: ["Doctor", "Nurse / Aesthetician"], room: "Procedure Room", active: true, pos: true, description: "Hydration and texture refinement.", contraindications: "Review active breakouts and allergies.", aftercare: "No sauna or direct sun exposure." },
  { id: "svc-rejuran", name: "Rejuran Therapy", category: "Injectables & Contour Enhancements", duration: 60, price: 15500, commission: "Doctor 10%", consumables: ["Skin Booster Vials"], branches: ["Mace BGC"], staff: ["Doctor"], room: "Procedure Room", active: true, pos: true, description: "Regenerative skin quality treatment.", contraindications: "Pregnancy or active infection.", aftercare: "Gentle skincare for 72 hours." },
  { id: "svc-mace-resurface", name: "Mace Resurface", category: "Laser Treatments & Energy-Based Devices", duration: 75, price: 8500, commission: "Laser 10%", consumables: ["Laser Tips"], branches: ["Mace BGC", "Mace Davao"], staff: ["Doctor", "Nurse / Aesthetician"], room: "Laser Room", active: true, pos: true, description: "Texture and acne scar resurfacing.", contraindications: "Photosensitivity or recent tanning.", aftercare: "Strict sunscreen and barrier care." },
  { id: "svc-ultralift", name: "Mace Ultralift", category: "Laser Treatments & Energy-Based Devices", duration: 90, price: 18000, commission: "Device 10%", consumables: ["Ultralift Cartridge"], branches: ["Mace BGC"], staff: ["Doctor", "Nurse / Aesthetician"], room: "Device Suite", active: true, pos: true, description: "Non-invasive lifting and tightening.", contraindications: "Metal implants in area need review.", aftercare: "Hydrate and avoid heat." },
  { id: "svc-diode", name: "Diode Hair Removal", category: "Laser Treatments & Energy-Based Devices", duration: 45, price: 4500, commission: "Laser 8%", consumables: ["Laser Tips"], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "Laser Room", active: true, pos: true, description: "Hair reduction treatment.", contraindications: "Recent waxing or photosensitive meds.", aftercare: "Avoid heat and exfoliation." },
  { id: "svc-glow-drip", name: "Glow Drip", category: "IV Drips", duration: 50, price: 6500, commission: "Nurse 8%", consumables: ["IV Glow Kit"], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "IV Lounge", active: true, pos: true, description: "Wellness drip for glow support.", contraindications: "Doctor review for kidney or heart conditions.", aftercare: "Hydrate after infusion." },
  { id: "svc-nad", name: "NAD+ IV Therapy", category: "IV Drips", duration: 90, price: 14500, commission: "Nurse 8%", consumables: ["IV Glow Kit"], branches: ["Mace BGC"], staff: ["Doctor", "Nurse / Aesthetician"], room: "IV Lounge", active: true, pos: true, description: "Advanced wellness infusion.", contraindications: "Requires medical clearance.", aftercare: "Rest and hydrate." },
  { id: "svc-package-glow", name: "Glow Maintenance Plan", category: "Packages", duration: 360, price: 18500, commission: "Package rule", consumables: [], branches: ["Mace BGC", "Mace Davao"], staff: ["Nurse / Aesthetician"], room: "Any", active: true, pos: true, description: "Six-session maintenance package.", contraindications: "Per included services.", aftercare: "Follow each session aftercare." },
];

export const initialClients = [
  {
    id: "cl-celine",
    fullName: "Celine Ann Hernandez",
    mobile: "0917 443 2210",
    email: "celine.hernandez@example.com",
    gender: "Female",
    birthday: "1992-09-14",
    address: "BGC, Taguig",
    city: "Taguig",
    emergency: "Marco Hernandez - 0917 200 9911",
    branch: "Mace BGC",
    source: "Website",
    referral: "MACE website",
    medicalNotes: "Sensitive skin. Prefers doctor review before injectables.",
    allergies: "None declared",
    contraindications: "Review before laser during active irritation.",
    skinConcerns: "Texture, dullness, early fine lines",
    treatmentGoals: "Natural glow and refreshed face",
    consentStatus: "Signed",
    marketingOptIn: true,
    preferredStaff: "Dr. Mace",
    tag: "VIP",
    retention: "Returning",
    lastVisit: "2026-07-01",
    nextVisit: "2026-07-08",
    balance: 0,
    packageBalance: "4 of 6 Glow Maintenance sessions",
    giftBalance: 0,
  },
  {
    id: "cl-mika",
    fullName: "Mika Santos",
    mobile: "0928 842 1180",
    email: "mika.santos@example.com",
    gender: "Female",
    birthday: "1995-02-21",
    address: "Makati City",
    city: "Makati",
    emergency: "Lia Santos - 0928 500 4422",
    branch: "Mace BGC",
    source: "Instagram",
    referral: "Instagram",
    medicalNotes: "First consultation. Asked for acne plan.",
    allergies: "Latex sensitivity",
    contraindications: "Avoid latex supplies.",
    skinConcerns: "Acne, congestion",
    treatmentGoals: "Clearer skin and maintenance routine",
    consentStatus: "Pending",
    marketingOptIn: true,
    preferredStaff: "Nurse Ana",
    tag: "New",
    retention: "New",
    lastVisit: "2026-06-28",
    nextVisit: "2026-07-05",
    balance: 1500,
    packageBalance: "None",
    giftBalance: 0,
  },
  {
    id: "cl-andrea",
    fullName: "Andrea Lee",
    mobile: "0916 092 8821",
    email: "andrea.lee@example.com",
    gender: "Female",
    birthday: "1988-11-08",
    address: "Davao City",
    city: "Davao",
    emergency: "Ben Lee - 0916 120 8877",
    branch: "Mace Davao",
    source: "Referral",
    referral: "Friend referral",
    medicalNotes: "Prefers non-invasive lifting treatments.",
    allergies: "None declared",
    contraindications: "None declared",
    skinConcerns: "Laxity, facial contour",
    treatmentGoals: "Lifted but natural result",
    consentStatus: "Signed",
    marketingOptIn: false,
    preferredStaff: "Dr. Aria Tan",
    tag: "Returning",
    retention: "Returning",
    lastVisit: "2026-06-21",
    nextVisit: "2026-07-10",
    balance: 4500,
    packageBalance: "1 of 3 Lift & Define sessions",
    giftBalance: 2000,
  },
  {
    id: "cl-trisha",
    fullName: "Trisha Uy",
    mobile: "0915 883 6174",
    email: "trisha.uy@example.com",
    gender: "Female",
    birthday: "1997-05-18",
    address: "Quezon City",
    city: "Quezon City",
    emergency: "Ana Uy - 0915 109 2117",
    branch: "Mace BGC",
    source: "Facebook",
    referral: "Facebook page",
    medicalNotes: "Acne scar program in progress.",
    allergies: "None declared",
    contraindications: "Avoid laser if skin is sunburned.",
    skinConcerns: "Acne marks, texture",
    treatmentGoals: "Smooth texture and less visible scars",
    consentStatus: "Signed",
    marketingOptIn: true,
    preferredStaff: "Nurse Bea",
    tag: "Follow-up",
    retention: "At risk",
    lastVisit: "2026-06-19",
    nextVisit: "2026-07-04",
    balance: 0,
    packageBalance: "3 of 4 Acne Recovery sessions",
    giftBalance: 0,
  },
];

export const initialAppointments = [
  { id: "ap-001", date: "2026-07-03", time: "09:30", clientId: "cl-mika", client: "Mika Santos", serviceId: "svc-consult", service: "Aesthetic Consultation", branch: "Mace BGC", room: "Room 1", staff: "Dr. Mace", status: "Confirmed", deposit: 0, notes: "First consult from Instagram.", internalNotes: "Offer acne protocol." },
  { id: "ap-002", date: "2026-07-03", time: "11:00", clientId: "cl-celine", client: "Celine Ann Hernandez", serviceId: "svc-skin-booster", service: "Skin Booster Treatment", branch: "Mace BGC", room: "Room 2", staff: "Nurse Ana", status: "Arrived", deposit: 2000, notes: "Maintenance session.", internalNotes: "Check hydration plan." },
  { id: "ap-003", date: "2026-07-03", time: "13:30", clientId: "cl-andrea", client: "Andrea Lee", serviceId: "svc-ultralift", service: "Mace Ultralift", branch: "Mace Davao", room: "Device Suite", staff: "Dr. Aria Tan", status: "Pending", deposit: 0, notes: "Client asked about contour results.", internalNotes: "Doctor review before device." },
  { id: "ap-004", date: "2026-07-03", time: "15:00", clientId: "cl-trisha", client: "Trisha Uy", serviceId: "svc-mace-resurface", service: "Mace Resurface", branch: "Mace BGC", room: "Laser Room", staff: "Nurse Bea", status: "Confirmed", deposit: 1000, notes: "Aftercare reminder needed.", internalNotes: "Patch test done." },
];

export const initialInventory = [
  { id: "inv-skin-booster", item: "Skin Booster Vials", sku: "INJ-SBV-10", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "vial", packQty: 10, beginning: 30, stock: 18, branch: "Mace BGC", location: "Cold storage", reorder: 10, expiry: "2026-11-30", batch: "SBV-2607", supplier: "Derma Supply PH", cost: 3200, price: 0 },
  { id: "inv-botox", item: "Botox Units", sku: "INJ-BTX-100", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "unit", packQty: 100, beginning: 30, stock: 9, branch: "Mace BGC", location: "Cold storage", reorder: 12, expiry: "2026-09-20", batch: "BTX-2605", supplier: "Aesthetic Med PH", cost: 240, price: 0 },
  { id: "inv-filler", item: "Filler Syringe", sku: "INJ-FLR-01", brand: "MACE Clinical", category: "Injectables", type: "Consumable", unit: "syringe", packQty: 1, beginning: 12, stock: 7, branch: "Mace BGC", location: "Cold storage", reorder: 5, expiry: "2026-10-15", batch: "FLR-2606", supplier: "Aesthetic Med PH", cost: 5800, price: 0 },
  { id: "inv-syringe", item: "Sterile Syringe Kit", sku: "SUP-SYK-01", brand: "MedSafe", category: "Supplies", type: "Consumable", unit: "kit", packQty: 1, beginning: 80, stock: 45, branch: "Mace BGC", location: "Procedure room", reorder: 25, expiry: "2027-01-12", batch: "SYK-2604", supplier: "MedSafe Supplies", cost: 90, price: 0 },
  { id: "inv-post-cream", item: "Post-care Cream", sku: "RTL-PCC-30", brand: "MACE Skin", category: "Retail", type: "Retail", unit: "tube", packQty: 1, beginning: 50, stock: 34, branch: "Mace Davao", location: "Retail shelf", reorder: 20, expiry: "2027-04-30", batch: "PCC-2607", supplier: "MACE Skin Lab", cost: 420, price: 1200, image: "/brand/products/post-care-cream.png" },
  { id: "inv-laser-tips", item: "Laser Tips", sku: "DEV-LTP-01", brand: "Device Care", category: "Device Consumables", type: "Consumable", unit: "tip", packQty: 1, beginning: 18, stock: 6, branch: "Mace Davao", location: "Laser room", reorder: 8, expiry: "2026-12-01", batch: "LTP-2602", supplier: "Device Care PH", cost: 950, price: 0 },
  { id: "inv-cleanser-kit", item: "Cleanser Travel Kit", sku: "RTL-CLK-01", brand: "MACE Skin", category: "Retail", type: "Retail", unit: "kit", packQty: 1, beginning: 36, stock: 24, branch: "Mace BGC", location: "Retail shelf", reorder: 12, expiry: "2027-02-18", batch: "CLK-2606", supplier: "MACE Skin Lab", cost: 520, price: 1500, image: "/brand/products/cleanser-travel-kit.png" },
  { id: "inv-iv-kit", item: "IV Glow Kit", sku: "IV-GLW-01", brand: "MACE Wellness", category: "IV Drips", type: "Consumable", unit: "kit", packQty: 1, beginning: 22, stock: 11, branch: "Mace BGC", location: "IV Lounge", reorder: 8, expiry: "2026-08-30", batch: "IVG-2605", supplier: "Wellness Supply PH", cost: 1800, price: 0 },
  { id: "inv-ultralift", item: "Ultralift Cartridge", sku: "DEV-ULT-01", brand: "MACE Devices", category: "Device Consumables", type: "Consumable", unit: "cartridge", packQty: 1, beginning: 10, stock: 4, branch: "Mace BGC", location: "Device suite", reorder: 4, expiry: "2027-05-01", batch: "ULT-2607", supplier: "Device Care PH", cost: 4200, price: 0 },
];

export const initialTreatments = [
  { id: "tr-001", clientId: "cl-celine", client: "Celine Ann Hernandez", date: "2026-07-01", service: "Skin Booster Treatment", provider: "Dr. Mace", room: "Room 2", preNotes: "Skin hydrated. Consent confirmed.", postNotes: "Mild redness expected.", consumables: "Skin Booster Vials, Sterile Syringe Kit", deviceSettings: "N/A", batch: "SBV-2607", consent: "Signed", followUp: "2026-07-08", outcome: "Good tolerance", satisfaction: "Very satisfied", photos: 2 },
  { id: "tr-002", clientId: "cl-trisha", client: "Trisha Uy", date: "2026-06-19", service: "Mace Resurface", provider: "Nurse Bea", room: "Laser Room", preNotes: "No sun exposure.", postNotes: "Aftercare explained.", consumables: "Laser Tips", deviceSettings: "Level 3, 2 passes", batch: "LTP-2602", consent: "Signed", followUp: "2026-07-04", outcome: "Texture improvement plan ongoing", satisfaction: "Satisfied", photos: 2 },
  { id: "tr-003", clientId: "cl-andrea", client: "Andrea Lee", date: "2026-06-21", service: "Mace Ultralift", provider: "Dr. Aria Tan", room: "Device Suite", preNotes: "Face mapping completed.", postNotes: "Mild tenderness.", consumables: "Ultralift Cartridge", deviceSettings: "Face protocol A", batch: "ULT-2607", consent: "Signed", followUp: "2026-07-10", outcome: "Initial lifting response", satisfaction: "Happy", photos: 0 },
];

export const initialPackages = [
  { id: "pkg-001", name: "Glow Maintenance Plan", clientId: "cl-celine", client: "Celine Ann Hernandez", sessions: 6, used: 2, expires: "2026-12-31", branch: "All branches", transferable: false, status: "Active", price: 18500 },
  { id: "pkg-002", name: "Acne Recovery Plan", clientId: "cl-trisha", client: "Trisha Uy", sessions: 4, used: 1, expires: "2026-10-30", branch: "Mace BGC", transferable: false, status: "Active", price: 14000 },
  { id: "pkg-003", name: "Lift & Define Plan", clientId: "cl-andrea", client: "Andrea Lee", sessions: 3, used: 0, expires: "2026-12-15", branch: "All branches", transferable: true, status: "Pending", price: 48000 },
];

export const initialGiftCertificates = [
  { id: "gc-001", code: "MACE-GLOW-1000", client: "Walk-in buyer", balance: 1000, expires: "2026-12-31", status: "Active" },
  { id: "gc-002", code: "MACE-FACE-5000", client: "Andrea Lee", balance: 2000, expires: "2026-11-30", status: "Partially used" },
];

export const initialLeads = [
  { id: "lead-001", name: "Janine Cruz", firstName: "Janine", lastName: "Cruz", mobile: "0917 771 2011", email: "janine.cruz@example.test", source: "Website", sourcePlatform: "Website", campaign: "July Skin Boosters", interest: "Skin Booster Treatment", concern: "Dryness before an event", status: "New Inquiry", priority: "High", score: 65, scoreReasons: JSON.stringify([{ points: 20, reason: "Identified service or treatment interest" }, { points: 10, reason: "Reachable contact method" }, { points: 15, reason: "Shared preferred appointment schedule" }]), owner: "Ria Lim", branch: "Mace BGC", assignedBranch: "Mace BGC", created: "2026-07-03", preferredDate: "2026-07-12", preferredTime: "15:00", nextAction: "Initial response", nextFollowUpAt: "2026-07-11T10:00:00.000Z", slaDueAt: "2026-07-03T01:15:00.000Z", permissionToContact: true, marketingConsent: false, privacyConsent: true, consentSource: "Website form", consentTimestamp: "2026-07-03T01:00:00.000Z", consentVersion: "website-v1", firstTouchSource: "Website", latestTouchSource: "Website", nextStep: "Call today" },
  { id: "lead-002", name: "Patricia Lim", firstName: "Patricia", lastName: "Lim", mobile: "0916 220 3412", source: "Instagram", sourcePlatform: "Instagram", campaign: "Botox Reel Inquiry", interest: "Botulinum Toxin Injections", concern: "Forehead lines", status: "Connected", priority: "Normal", score: 55, scoreReasons: JSON.stringify([{ points: 20, reason: "Identified service or treatment interest" }, { points: 10, reason: "Reachable contact method" }, { points: 5, reason: "Campaign attribution available" }]), owner: "Mika Santos", branch: "Mace BGC", assignedBranch: "Mace BGC", created: "2026-07-02", lastContactedAt: "2026-07-02T08:00:00.000Z", firstRespondedAt: "2026-07-02T08:00:00.000Z", nextAction: "Send estimate", nextFollowUpAt: "2026-07-11T06:30:00.000Z", followUpCount: 1, slaDueAt: "2026-07-02T07:05:00.000Z", permissionToContact: true, marketingConsent: false, privacyConsent: true, consentSource: "Instagram inquiry", consentTimestamp: "2026-07-02T07:00:00.000Z", firstTouchSource: "Instagram", latestTouchSource: "Instagram", nextStep: "Send estimate" },
  { id: "lead-003", name: "Elaine Tan", firstName: "Elaine", lastName: "Tan", mobile: "0927 881 3000", source: "Facebook", sourcePlatform: "Meta Facebook", campaign: "Resurface Lead Ad", formId: "fb-form-resurface", externalLeadId: "fb-lead-elaine-001", interest: "Mace Resurface", status: "Appointment Booked", priority: "High", score: 78, scoreReasons: JSON.stringify([{ points: 20, reason: "Identified service or treatment interest" }, { points: 15, reason: "Shared preferred appointment schedule" }, { points: 8, reason: "Routed to a branch" }]), owner: "Nurse Bea", branch: "Mace Davao", assignedBranch: "Mace Davao", created: "2026-07-01", linkedAppointmentId: "ap-004", preferredDate: "2026-07-12", preferredTime: "13:30", nextAction: "Confirm deposit", nextFollowUpAt: "2026-07-11T07:00:00.000Z", followUpCount: 1, permissionToContact: true, marketingConsent: true, privacyConsent: true, consentSource: "Facebook lead form", consentTimestamp: "2026-07-01T05:00:00.000Z", firstTouchSource: "Facebook Lead Ad", latestTouchSource: "Facebook Lead Ad", nextStep: "Confirm deposit" },
  { id: "lead-004", name: "Rachelle Go", firstName: "Rachelle", lastName: "Go", mobile: "0918 001 8821", email: "rachelle.go@example.test", source: "Website", sourcePlatform: "Website", campaign: "Ultralift Landing Page", interest: "Mace Ultralift", concern: "Jawline and cheeks", status: "Follow-Up", priority: "Normal", score: 63, scoreReasons: JSON.stringify([{ points: 20, reason: "Identified service or treatment interest" }, { points: 15, reason: "Complete phone and email" }, { points: 5, reason: "Campaign attribution available" }]), owner: "Mika Santos", branch: "Mace BGC", assignedBranch: "Mace BGC", created: "2026-06-30", nextAction: "Second follow-up", nextFollowUpAt: "2026-07-10T09:00:00.000Z", followUpCount: 2, slaDueAt: "2026-06-30T03:15:00.000Z", permissionToContact: true, marketingConsent: false, privacyConsent: true, consentSource: "Landing page", consentTimestamp: "2026-06-30T03:00:00.000Z", firstTouchSource: "Website", latestTouchSource: "Website Consultation Form", nextStep: "Follow up tomorrow" },
];

export const initialStaff = [
  { id: "st-dr-mace", name: "Dr. Mace", role: "Doctor", branch: "Mace BGC", schedule: "9:00 AM - 5:00 PM", commissionType: "Doctor rate", commissionRate: 12, services: "Injectables, consultations", status: "Available", attendance: "Clocked in", employmentDate: "2022-01-05", phone: "0917 109 8462" },
  { id: "st-aria", name: "Dr. Aria Tan", role: "Doctor", branch: "Mace Davao", schedule: "10:00 AM - 6:00 PM", commissionType: "Doctor rate", commissionRate: 10, services: "Devices, consultations", status: "Available", attendance: "Clocked in", employmentDate: "2024-08-12", phone: "0917 334 2218" },
  { id: "st-ana", name: "Nurse Ana", role: "Nurse / Aesthetician", branch: "Mace BGC", schedule: "10:00 AM - 7:00 PM", commissionType: "Skin care", commissionRate: 8, services: "Facials, IV drips", status: "In treatment", attendance: "Clocked in", employmentDate: "2023-04-20", phone: "0918 220 7719" },
  { id: "st-bea", name: "Nurse Bea", role: "Nurse / Aesthetician", branch: "Mace Davao", schedule: "8:00 AM - 5:00 PM", commissionType: "Device care", commissionRate: 8, services: "Lasers, facials", status: "Available", attendance: "Clocked in", employmentDate: "2023-10-03", phone: "0916 777 8822" },
  { id: "st-ria", name: "Ria Lim", role: "Receptionist", branch: "Mace BGC", schedule: "9:00 AM - 6:00 PM", commissionType: "N/A", commissionRate: 0, services: "Front desk", status: "Available", attendance: "Clocked in", employmentDate: "2025-02-15", phone: "0917 600 8891" },
];

export const initialExpenses = [
  { id: "ex-001", date: "2026-07-02", name: "Clinic supplies", category: "Supplies", branch: "Mace BGC", amount: 12400, method: "Bank Transfer", approver: "Owner", status: "Approved", notes: "Monthly replenishment.", receipt: "Attached" },
  { id: "ex-002", date: "2026-07-01", name: "Utilities", category: "Utilities", branch: "Mace Davao", amount: 8900, method: "Cash", approver: "Branch Manager", status: "Approved", notes: "Electric and water.", receipt: "Attached" },
  { id: "ex-003", date: "2026-06-30", name: "Training refresh", category: "Training", branch: "Mace BGC", amount: 18000, method: "Credit Card", approver: "Owner", status: "For approval", notes: "Device protocol refresh.", receipt: "Pending" },
  { id: "ex-004", date: "2026-06-28", name: "Instagram campaign", category: "Marketing", branch: "All branches", amount: 22000, method: "Credit Card", approver: "Owner", status: "Approved", notes: "Promo ads.", receipt: "Attached" },
];

export const initialTransactions = [
  { id: "txn-260703-001", invoice: "MACE-260703-001", date: "2026-07-03", time: "10:15", client: "Walk-in", branch: "Mace BGC", staff: "Nurse Ana", items: [{ name: "Mace Signature Facial", type: "Service", qty: 1, price: 3200 }], subtotal: 3200, discount: 0, total: 3200, payments: [{ method: "GCash", amount: 3200 }], status: "Paid", notes: "Walk-in service." },
  { id: "txn-260702-001", invoice: "MACE-260702-001", date: "2026-07-02", time: "14:20", client: "Celine Ann Hernandez", branch: "Mace BGC", staff: "Dr. Mace", items: [{ name: "Skin Booster Treatment", type: "Service", qty: 1, price: 9500 }, { name: "Post-care Cream", type: "Product", qty: 1, price: 1200 }], subtotal: 10700, discount: 700, total: 10000, payments: [{ method: "Cash", amount: 6000 }, { method: "Credit Card", amount: 4000 }], status: "Paid", notes: "VIP courtesy discount." },
  { id: "txn-260701-002", invoice: "MACE-260701-002", date: "2026-07-01", time: "17:05", client: "Andrea Lee", branch: "Mace Davao", staff: "Dr. Aria Tan", items: [{ name: "Mace Ultralift", type: "Service", qty: 1, price: 18000 }], subtotal: 18000, discount: 0, total: 18000, payments: [{ method: "Bank Transfer", amount: 13500 }], status: "Partial", notes: "Balance due on next visit." },
];

export const initialDiscounts = [
  { id: "disc-senior", name: "Senior Citizen", type: "Percentage", value: 20, active: true, permission: "Cashier", applicable: "Services and products", expiry: "None", usage: 8 },
  { id: "disc-pwd", name: "PWD", type: "Percentage", value: 20, active: true, permission: "Cashier", applicable: "Services and products", expiry: "None", usage: 4 },
  { id: "disc-vip", name: "VIP", type: "Fixed amount", value: 700, active: true, permission: "Branch Manager", applicable: "Selected clients", expiry: "2026-12-31", usage: 12 },
  { id: "disc-owner", name: "Owner's Discount", type: "Percentage", value: 100, active: true, permission: "Owner", applicable: "Owner approval only", expiry: "None", usage: 2 },
  { id: "disc-birthday", name: "Birthday Promo", type: "Percentage", value: 10, active: true, permission: "Receptionist", applicable: "Birthday month", expiry: "2026-12-31", usage: 15 },
];

export const initialSmsTemplates = [
  { id: "sms-confirm", name: "Appointment confirmation", category: "Appointment", text: "Hi {{client}}, your MACE appointment for {{service}} is confirmed on {{date}} at {{time}}. Reply YES to confirm.", active: true },
  { id: "sms-reminder", name: "Appointment reminder", category: "Appointment", text: "Hi {{client}}, this is your gentle reminder for your MACE visit tomorrow at {{time}}. We love your face.", active: true },
  { id: "sms-aftercare", name: "Post-treatment follow-up", category: "Aftercare", text: "Hi {{client}}, thank you for visiting MACE. Please follow your aftercare notes and message us for any concerns.", active: true },
  { id: "sms-birthday", name: "Birthday greeting", category: "Marketing", text: "Happy birthday month, {{client}}. A beautiful month deserves a MACE glow.", active: true },
  { id: "sms-winback", name: "Win-back campaign", category: "Marketing", text: "Hi {{client}}, it has been a while. Book your personalized care session with MACE this week.", active: true },
];

export const initialCampaigns = [
  {
    id: "cmp-001",
    name: "July Glow Reminder",
    segment: "Inactive clients",
    channel: "SMS",
    templateId: "sms-winback",
    subject: "Your MACE glow is waiting",
    message: "Hi {{client}}, it has been a while. Book your personalized care session with MACE this week.",
    sent: 180,
    booked: 24,
    credits: 180,
    status: "Sent",
  },
  {
    id: "cmp-002",
    name: "Birthday Month Care",
    segment: "Birthday month",
    channel: "SMS",
    templateId: "sms-birthday",
    subject: "Birthday month care from MACE",
    message: "Happy birthday month, {{client}}. A beautiful month deserves a MACE glow.",
    sent: 42,
    booked: 9,
    credits: 42,
    status: "Scheduled",
  },
  {
    id: "cmp-003",
    name: "Skin Booster Upsell",
    segment: "Facial clients",
    channel: "Email",
    templateId: "",
    subject: "Skin booster appointments are open",
    message: "Hi {{client}}, your next skin booster session can help keep your glow fresh. Reply to this email to reserve your preferred time.",
    sent: 0,
    booked: 0,
    credits: 0,
    status: "Draft",
  },
];

export const initialSettings = {
  company: "MACE by Dr. Mace",
  productName: "MACE ClinicOS",
  currency: "PHP",
  taxMode: "VAT exclusive",
  taxRate: 12,
  receiptFooter: "The brand behind beautiful faces.",
  invoicePrefix: "MACE",
  smsCredits: 8400,
  backup: "Daily backup-ready",
  hiddenSaasPlans: true,
  paymentMethods: ["Cash", "Credit Card", "Debit Card", "GCash", "Maya", "Bank Transfer", "Check", "Gift Certificate", "Account Balance"],
  expenseCategories: ["Salary", "Supplies", "Utilities", "Rent", "Marketing", "Training", "Equipment", "Maintenance", "Professional fees", "Other"],
  productCategories: ["Injectables", "Retail", "Device Consumables", "Supplies", "IV Drips"],
  serviceCategories,
};
